### ISSUE TITLE
[no-ticket] Design a section to show the Nigma Team

### ISSUE THREAD

**Issue by apoclyps** [Nigmaio/nigma.io#14]
### Problem
The Nigma team currently do not have any visibility on the website. A new section should be added to show the team members and provide a short description of the team.

Acceptance Criteria
- Contains 1 founder, 2 city leads, 3 ambassadors. (does not need to contain real information for the purpose of the design).
- Should contain an Image, A title ( e.g. founder), and a short description such as (Software Engineer @ Company)

**Comment by kvsm** [comment]
I'll take a swing at this.
