### ISSUE TITLE
[no-ticket] Replace font-awesome files with a CDN

### ISSUE THREAD

**Issue by apoclyps** [Nigmaio/nigma.io#2]
### Problem
Hosting font-awesome is not required when a CDN can be used.

### Acceptance Criteria
- font-awesome is removed from the repository.
- font-awesome is provided via a CDN.

### Resources
- CDN: https://www.bootstrapcdn.com/fontawesome/

**Comment by rinkal-rohara** [comment]
I am taking this

**Comment by apoclyps** [comment]
The Font awesome folder still needs to be removed from the repo - if anyone wants to pick this up as part of #21

**Comment by nirmalks** [comment]
#24 [Removed font awesome direcotory](https://github.com/Nigmaio/nigma.io/pull/24)
