### ISSUE TITLE
[no-ticket] Replace Bootstrap CSS files with a CDN

### ISSUE THREAD

**Issue by apoclyps** [Nigmaio/nigma.io#3]
### Problem
Hosting bootstrap CSS is not required when a CDN can be used.

### Acceptance Criteria
- bootstrap CSS is removed from the repository.
- bootstrap CSS is provided via a CDN.
- bootstrap CSS is using a minified source and the latest version

### Resources
- CDN: https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css

**Comment by rinkal-rohara** [comment]
I am taking this.
