### ISSUE TITLE
[no-ticket] Remove unused images

### ISSUE THREAD

**Issue by apoclyps** [Nigmaio/nigma.io#6]
### Problem
The repository contains images that are no longer used. These should be removed.

### Acceptance Criteria
- The `img` folder contains images that are not used. Remove these
- Confirm the images are not used in the code base.

### Resources
- Images that do not appear to be used: https://github.com/Nigmaio/nigma.io/tree/master/img/portfolio

**Comment by alangordon** [comment]
Taking this
