### ISSUE TITLE
[no-ticket] Replace jquery files with a CDN

### ISSUE THREAD

**Issue by apoclyps** [Nigmaio/nigma.io#8]
### Problem
Hosting jquery is not required when a CDN can be used.

### Acceptance Criteria
- jquery is removed from the repository.
- jquery is provided via a CDN.
- jquery is using a minified source and the latest version

### Resources
- CDN: https://cdnjs.com/libraries/jquery/

**Comment by nirmalks** [comment]
I can take up this issue.

**Comment by ayushjn20** [comment]
I have completed the required changes, please review and accept my pull request

**Comment by apoclyps** [comment]
@ayushjn20 your PR looks good however it contains more changes than requested. I'd like to allow more beginners to tackle smaller PRS so I'm gonna hold off on merging this until some of the individual issues are addressed separately.

**Comment by kshitij98** [comment]
I am working on this issue.
