### ISSUE TITLE
[no-ticket] Create README content

### ISSUE THREAD

**Issue by apoclyps** [Nigmaio/nigma.io#9]
### Problem
The readme does not provide any information at present.

### Acceptance Criteria
- It should contain a description of the Nigma community
- It should contain instructions on 'Getting setup'
- It should contain instructions on 'How to contribute'

**Comment by LunarWatcher** [comment]
This isn't a good first issue for someone who doesn't know about the community. 'How to contribute' is a separate file (isn't in readme)

**Comment by apoclyps** [comment]
@LunarWatcher you're right; that isn't an appropriate label. Ideally, we were hoping more community members would address some of the issues however as it's public anyone can pick it up. The website and facebook groups contain information related to the community but I've removed the label to avoid confusion.
